name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/pnpm:v1.4.0
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: pnpm i
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm t
